---
- id: taplo-format
  name: check TOML format with Taplo
  description: Check TOML format with Taplo
  entry: taplo format
  language: system
  types: [toml]

- id: taplo-lint
  name: lint TOML with Taplo
  description: Lint TOML with Taplo
  entry: taplo lint
  language: system
  types: [toml]
